import datetime
now=datetime.datetime.now()
print(now)
hour=now.strftime("Hour:%H")
print(hour)
minute=now.strftime("Minute:%M")
print(minute)
sec=now.strftime("Second:%S")
print(sec)
year=now.strftime("Year:%y")
print(year)
mon=now.strftime("Month:%m")
print(mon)
date=now.strftime("Date:%d")
print(date)
